<?php include("include/header.php") ?>
<?php include("include/nav.php") ?>
<?php include("include/menu.students.php") ?>
<?php include("include/myproject.php") ?>
<?php include("include/allproject.php") ?>
<?php include("include/information.teachers.php") ?>
<?php include("include/tool-finding-teacher.php") ?>
<?php include("include/finding-job.php") ?>
<?php include("include/footer.php") ?>
